[database]
url = "sqlite:db_sqlite.db"

[hash_size]
size_password = 32
size_auth_id = 16

[logging]
level = 20
expiration_date = 3
debug_expiration_date = 3
uvicorn_logging_disable = true
debug = "[<b>{time: DD/MM/YY HH:mm:ss}</>]  [<g>{level}</>] {module} | {function} | line:{line: >3} | {message}"
error = "[<b>{time:DD/MM/YY HH:mm:ss}</>]  [<r>{level}</>] {module} | {function} | line:{line: >3} | {message}"
info = "[<b>{time:DD/MM/YY HH:mm:ss}</>]  [<e>{level}</>]  {message}"

[limits]
messages = 100
users = 100

[api]
max_version = "1.9"
min_version = "1.0"
