name: Push coverage to Coveralls

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pipenv
      run: |
        python -m pip install pipenv
    - name: Install dependencies
      run: |
        pipenv install --dev
    - name: Install coveralls-python
      run: |
        pipenv install coveralls==3.3.1
    - name: Create coverage report
      run: |
        pipenv run coverage -m unittest discover tests
    - name: Push report to coveralls.io
      run: |
        pipenv run coveralls
