name: Build and push docs
on: 
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipx tool
        run: |
          pip list

      - name: Install poetry tool
        run: |
          pipx install poetry

      - name: Install dependencies
        run: |
          poetry install
          
      - name: Create config for server
        run: |
          mv example_config.ini config.ini
          
      - name: Build docs
        run: |
          cd docs
          poetry run make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: docs
          folder: ./docs/build/html/
