name: Build and push docs
on: push
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev
          
      - name: Create config for server
        run: |
          mv example_config.ini config.ini
          
      - name: Build docs
        run: |
          cd docs
          pipenv run make html
          cd ../

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: docs
          folder: ./docs/build/html/
