name: Test, Linting and Push to Coveralls

on: [push, pull_request]

jobs:
  test-and-linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install pipenv
      run: |
        pip install pipenv
      
    - name: Install dependencies
      run: |
        pipenv install --dev
        
    - name: Create config for server
      run: |
        mv example_config.ini config.ini
                
    - name: Run tests
      run: |
        pipenv run python -m unittest discover tests
        
    - name: Linting code
      run: |
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Install coveralls-python
      run: |
        pipenv install coveralls==3.3.1

    - name: Create coverage report
      run: |
        pipenv run coverage run -m unittest discover tests

    - name: Push report to coveralls.io
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pipenv run coveralls --service=github
